### ISSUE TITLE
Failing to add item

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#49] opened 2017-12-15 11:53 UTC
Getting an undocumented 400 error when attempting to add an item.

It's returning a "Timed out and no cache could be used" json error, yet it's a 400 instead of 500 error.

**Comment by steve-compassdigital** [comment] 2017-12-15 11:53
12-15 06:49:43.984 20036-14522/io.compassdigital.bonapp D/OkHttp: --> POST https://api.compassdigital.org/v1/shoppingcart/ HTTP/1.1
12-15 06:49:43.984 20036-14522/io.compassdigital.bonapp D/OkHttp: Content-Type: application/json; charset=UTF-8
12-15 06:49:43.984 20036-14522/io.compassdigital.bonapp D/OkHttp: Content-Length: 98
12-15 06:49:43.984 20036-14522/io.compassdigital.bonapp D/OkHttp: {"brand":"B5XY4Aq2ljsd4PYAQp70HB92M8jO0v","menu":"KBmKZRveqvCzv0GAQDpPTe2XzKO9R9fWvZdPJNkNuqgdpe"}
12-15 06:49:43.984 20036-14522/io.compassdigital.bonapp D/OkHttp: --> END POST (98-byte body)
12-15 06:49:44.218 20036-14522/io.compassdigital.bonapp D/OkHttp: <-- HTTP/1.1 200  (233ms)
12-15 06:49:44.218 20036-14522/io.compassdigital.bonapp D/OkHttp: content-type: application/json; charset=utf-8
12-15 06:49:44.218 20036-14522/io.compassdigital.bonapp D/OkHttp: content-length: 257
12-15 06:49:44.218 20036-14522/io.compassdigital.bonapp D/OkHttp: date: Fri, 15 Dec 2017 11:49:45 GMT
12-15 06:49:44.218 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-requestid: 0b536635-e18e-11e7-bd03-31806002fc70
12-15 06:49:44.218 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-x-amzn-requestid: 0b564c1e-e18e-11e7-98d1-b12a76e39f47
12-15 06:49:44.218 20036-14522/io.compassdigital.bonapp D/OkHttp: access-control-allow-origin: *
12-15 06:49:44.218 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-content-length: 257
12-15 06:49:44.219 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-connection: keep-alive
12-15 06:49:44.219 20036-14522/io.compassdigital.bonapp D/OkHttp: via: 1.1 beac5709ceeeaf96d399084af8eedb9c.cloudfront.net (CloudFront), 1.1 6b0059de423570ad76d9b5ffb119b833.cloudfront.net (CloudFront)
12-15 06:49:44.219 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-trace-id: sampled=0;root=1-5a33b6d8-c1c4a6a503b43dc3ba8dfaf6
12-15 06:49:44.219 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-date: Fri, 15 Dec 2017 11:49:45 GMT
12-15 06:49:44.219 20036-14522/io.compassdigital.bonapp D/OkHttp: x-cache: Miss from cloudfront
12-15 06:49:44.219 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amz-cf-id: XecnFlBreGvBcIhg2RQyLbLnhZEG46LGHxg2lL-palfCpWA_ryzrdQ==
12-15 06:49:44.219 20036-14522/io.compassdigital.bonapp D/OkHttp: OkHttp-Sent-Millis: 1513338583985
12-15 06:49:44.219 20036-14522/io.compassdigital.bonapp D/OkHttp: OkHttp-Received-Millis: 1513338584217
12-15 06:49:44.220 20036-14522/io.compassdigital.bonapp D/OkHttp: {"brand":"B5XY4Aq2ljsd4PYAQp70HB92M8jO0v","menu":"KBmKZRveqvCzv0GAQDpPTe2XzKO9R9fWvZdPJNkNuqgdpe","id":"319WpK3GpDTy5NkMgY11hq5dGw9NqRUo1qDNjZ9RhyYElRwyPlFREWPgwm94SEM029j","date":{"created":"2017-12-15T11:49:45.001Z","modified":"2017-12-15T11:49:45.001Z"}}
12-15 06:49:44.220 20036-14522/io.compassdigital.bonapp D/OkHttp: <-- END HTTP (257-byte body)
12-15 06:49:44.246 20036-14522/io.compassdigital.bonapp D/OkHttp: --> PUT https://api.compassdigital.org/v1/shoppingcart/319WpK3GpDTy5NkMgY11hq5dGw9NqRUo1qDNjZ9RhyYElRwyPlFREWPgwm94SEM029j HTTP/1.1
12-15 06:49:44.246 20036-14522/io.compassdigital.bonapp D/OkHttp: Content-Type: application/json; charset=UTF-8
12-15 06:49:44.246 20036-14522/io.compassdigital.bonapp D/OkHttp: Content-Length: 106
12-15 06:49:44.247 20036-14522/io.compassdigital.bonapp D/OkHttp: {"items":[{"id":"ME5Bg4vzXvI0gAYl3aoXFL64qjeq1Pt0ZM7mDo7rCa6NqQ1gKwIYYPp2Pej","options":[],"quantity":1}]}
12-15 06:49:44.247 20036-14522/io.compassdigital.bonapp D/OkHttp: --> END PUT (106-byte body)
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: <-- HTTP/1.1 400  (5705ms)
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: content-type: application/json; charset=utf-8
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: content-length: 48
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: date: Fri, 15 Dec 2017 11:49:50 GMT
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-requestid: 0b7b39b9-e18e-11e7-ade1-d9ac6d59b753
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-x-amzn-requestid: 0b7f5887-e18e-11e7-9c0d-3731cb090c67
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: access-control-allow-origin: *
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-content-length: 48
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-connection: keep-alive
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: via: 1.1 a10b46646fb5e4df7f1ca09cba817dc7.cloudfront.net (CloudFront), 1.1 6b0059de423570ad76d9b5ffb119b833.cloudfront.net (CloudFront)
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-trace-id: sampled=0;root=1-5a33b6d9-51a268d07c58d9bbe26ca000
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-date: Fri, 15 Dec 2017 11:49:50 GMT
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: x-cache: Error from cloudfront
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: x-amz-cf-id: k7AyQsyTewgTA7GbxAIr9p8TIiNzqERB4hdWl7E0nTn6EkBA1kcX2A==
12-15 06:49:49.982 20036-14522/io.compassdigital.bonapp D/OkHttp: OkHttp-Sent-Millis: 1513338584248
12-15 06:49:49.983 20036-14522/io.compassdigital.bonapp D/OkHttp: OkHttp-Received-Millis: 1513338589981
12-15 06:49:49.984 20036-14522/io.compassdigital.bonapp D/OkHttp: {"error":"Timed out and no cache could be used"}
12-15 06:49:49.984 20036-14522/io.compassdigital.bonapp D/OkHttp: <-- END HTTP (48-byte body)

**Comment by jonathankeebler** [comment] 2017-12-15 12:25
Thanks for the detailed ticket. We’ll check it out

________________________________

**Comment by ios-git** [comment] 2017-12-18 15:36
I am getting this error when i call add item to basket. but, if i call get basket "https://api.compassdigital.org/v1/shoppingcart/NePOXq8jXASApGE3OlOEulG8EP4vmzSyGE3joDlLUNqk1YlMXRClEDNWM08qtag6Qwe" then i am getting item. 


Add item to basket error: <NSHTTPURLResponse: 0x604000a29860> { URL: https://api.compassdigital.org/v1/shoppingcart/NePOXq8jXASApGE3OlOEulG8EP4vmzSyGE3joDlLUNqk1YlMXRClEDNWM08qtag6Qwe } { status code: 400, headers {
    "Access-Control-Allow-Origin" = "*";
    "Content-Length" = 48;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 18 Dec 2017 15:28:28 GMT";
    Via = "1.1 521677cb737ea195cb873db955bcc307.cloudfront.net (CloudFront), 1.1 84820c205c4006ef1b5d69dead59ca8e.cloudfront.net (CloudFront)";
    "x-amz-cf-id" = "VqdkCaJriCrcEj5FC5erw5NB67Ktz8ntYDueVhJ_kLHQlRvyIGqMGQ==";
    "x-amzn-remapped-connection" = "keep-alive";
    "x-amzn-remapped-content-length" = 48;
    "x-amzn-remapped-date" = "Mon, 18 Dec 2017 15:28:28 GMT";
    "x-amzn-remapped-x-amzn-requestid" = "157638a5-e408-11e7-a7d1-b5eb2a58b60b";
    "x-amzn-requestid" = "15732b6c-e408-11e7-9bc9-d3fc5c70f222";
    "x-amzn-trace-id" = "sampled=0;root=1-5a37de96-13d334024e886adeabbca019";
    "x-cache" = "Error from cloudfront";
} }  
reason:Unknown 
statuscode: 400

**Comment by coho1988** [comment] 2017-12-18 19:38
^^ above was from suman. 
Issue is: we add to cart. we get this response above. But when we check the cart itself, the item has been successfully added.

**Comment by jonathankeebler** [comment] 2017-12-18 20:08
@coho1988 Do we know what they were trying to add to the basket? What was the JSON they PUT to server?

**Comment by jonathankeebler** [comment] 2017-12-18 20:12
I'm seeing this error every now and again in the logs: Could not add items to the shopping cart. They did not appear to be in menu KBmKZRveqvCzv0GAQDpPTe2XzKeDNNiWvZdPJNkNuqgdpq

**Comment by steven-tucker** [comment] 2017-12-18 20:18
PUT: https://api.compassdigital.org/v1/shoppingcart/319WpK3GpDTy5NkMgY11hq5dGw9NqRUo1qDNjZ9RhyYElRwyPlFREWPgwm94SEM029j

{"items":[{"id":"ME5Bg4vzXvI0gAYl3aoXFL64qjeq1Pt0ZM7mDo7rCa6NqQ1gKwIYYPp2Pej","options":[],"quantity":1}]}

**Comment by steven-tucker** [comment] 2017-12-18 20:19
This error is occurring 100% of the calls on every item.

**Comment by jonathankeebler** [comment] 2017-12-18 20:34
Does this call work for you?
```
curl --request PUT "https://api.compassdigital.org/v1/shoppingcart/319WpK3GpDTy5NkMgY11hq5dGw9NqRUo1qDNjZ9RhyYElRwyPlFREWPgwm94SEM029j" \
    --header "Content-Type: application/json" \
    --header "Accept: application/json" \
    --data '{"items":[{"id":"ME5Bg4vzXvI0gAYl3aoXFL64qjeq1Pt0ZM7mDo7rCa6NqQ1gKwIYYPp2Pej","quantity":1}]}'

**Comment by jonathankeebler** [comment] 2017-12-18 22:32
@steven-tucker I think I found the bug that was causing this. It should be fixed now. If not, please re-open. Thanks

**Comment by suman-cdl** [comment] 2017-12-19 07:09
Add Item To Basket --> 

Request Url:
https://api.compassdigital.org/v1/shoppingcart/WOaKJ4WZJ0cGON3WDrXjTG6Ry1vk1eH9y9BMwOA2FzX89L3jGdSva4j2ELa7ClJa4YQ

Parameters:
{"items" : [{"id" : "p61vEp4g34Tqdjkm5az6Fr4JWwBMyYU3Rq9Xy19KTvXj1Y80eEcNNOd5OJk", "quantity" : 1,"options" : [{"label" : "scones","items" : ["G2WGR5QJMQizW4E9yLA2frzmdww9k4UGdo2WgZlriQyee5Z6WvTpoZNy9NDeTeR4my7"]},{"label" : "muffins","items" : ["z03ykPpQDpcjK4z7a9rXIMlqGmmgXOiYPQNZOz0gs5oww1RqlOfEN1gPGg2MceZPEk6"]}]}]}

**Comment by jonathankeebler** [comment] 2017-12-19 14:05
Did it happen again? I need more details @suman-cdl

**Comment by suman-cdl** [comment] 2017-12-19 14:14
it works fine now.

**Comment by jonathankeebler** [comment] 2017-12-19 14:15
When you posted that request this morning, did it not work?

________________________________

**Comment by suman-cdl** [comment] 2017-12-19 14:20
time out problem was there so i posted with url request.

**Comment by steven-tucker** [comment] 2017-12-19 21:29
A timeout that still adds will be a problem. If it fails, it should be a full fail. timeout will prompt a retry which will have double add. If this is still happening, it should be logged as a new bug.

**Comment by jonathankeebler** [comment] 2017-12-19 21:46
@suman-cdl When it times out, are you getting an error response? I looked at every single PUT shoppingcart request today. I saw one at 2017-12-19T07:08:04.578Z that took 3.5s to complete, but the other ones all completed <1s. Could 3.5s be timing out your client library?

If you are getting an error message from us, can you please send me a copy of the exact response you get. Thanks

**Comment by suman-cdl** [comment] 2017-12-20 06:39
@jonathankeebler i have checked this in library it is because of connection time out set in library. and now not a single time i am getting connection timeout error. so the issue is solved.
thanks.

**Comment by jonathankeebler** [comment] 2017-12-20 13:57
Awesome!

**Closed by jonathankeebler** 2017-12-20 13:57 UTC
